# Generated by Django 5.2.11 on 2026-04-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cattle",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cattle",
                "verbose_name_plural": "Cattle",
            },
        ),
    ]
