# Generated by Django 5.2.11 on 2026-02-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("worker", "Worker"),
                ],
                default="owner",
                max_length=20,
            ),
        ),
    ]
