# Generated by Django 5.2.11 on 2026-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_farm_location_alter_farm_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
