# Generated by Django 5.2.11 on 2026-02-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilkProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(db_index=True)),
                ("liters", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cattle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_records",
                        to="cattle.cattle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cattle", "date_time"),
                        name="unique_milk_record_per_session",
                    )
                ],
            },
        ),
    ]
