# Generated by Django 5.2.11 on 2026-04-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="milkproduction",
            options={
                "ordering": ["-date_time"],
                "verbose_name": "Milk Records",
                "verbose_name_plural": "Milk Records",
            },
        ),
    ]
